import { RouterDevice, BillingPlan } from '../types';

export function generateFullMikrotikScript(router: RouterDevice, plans: BillingPlan[]): string {
  const plansScript = plans
    .map(
      (p) =>
        `/ip hotspot user profile add name="${p.id}" rate-limit="${p.rateLimit}" shared-users=${p.sharedUsers} session-timeout=${p.validityMinutes}m keepalive-timeout=2m transparent-proxy=yes status-autorefresh=1m add-mac-cookie=yes mac-cookie-timeout=1d on-login=":log info \\"XCLOUD: User \\$user logged into ${p.name}\\""`
    )
    .join('\n');

  return `# ====================================================================
# XCLOUD TANZANIA - MIKROTIK RB941-2nD (hAP lite) & ROUTEROS v7 SCRIPT
# Location: ${router.name} | Generated: ${new Date().toISOString()}
# Architecture: ${router.architecture} | Tunnel IP: ${router.tunnelIp}
# ====================================================================

# 1. IDENTITY & TIMEZONE SETUP (TANZANIA EAT UTC+3)
/system identity set name="${router.name}"
/system clock set time-zone-name=Africa/Dar_es_Salaam
/system ntp client set enabled=yes
/system ntp client servers add address=time.cloudflare.com

# 2. XCLOUD REMOTE WIREGUARD TUNNEL SETUP
/interface wireguard add name=wg-xcloud listen-port=51820 private-key="AutoGeneratedOnRouterOrCopyHere==" comment="XCloud Cloud Interface"
/ip address add address=${router.tunnelIp}/24 interface=wg-xcloud network=10.8.0.0
/interface wireguard peers add interface=wg-xcloud public-key="${router.wireguardStatus.publicKey}" endpoint-address="vpn-tz1.xcloud.co.tz" endpoint-port=51820 allowed-address=10.8.0.0/24,192.168.88.0/24 persistent-keepalive=25s comment="XCloud Central Hub"

# 3. MIKROTIK API & MANAGEMENT PORTS
/ip service set api port=${router.apiConfig.port} disabled=no address=0.0.0.0/0
/ip service set api-ssl port=${router.apiConfig.sslPort} disabled=no
/ip service set www port=${router.apiConfig.restPort} disabled=no
/user group add name=xcloud_group policy=read,write,policy,test,api,sensitive
/user add name="${router.apiConfig.username}" group=xcloud_group password="XCloudTzSecPass2026!" comment="XCloud Cloud Agent User"

# 4. RADIUS SERVER INTEGRATION
/radius add service=hotspot address=${router.radiusConfig.serverIp} secret="${router.radiusConfig.secret}" authentication-port=${router.radiusConfig.authPort} accounting-port=${router.radiusConfig.acctPort} timeout=3000ms comment="XCloud Radius TZ"
/radius incoming set accept=yes port=3799

# 5. HOTSPOT SERVER & USER PROFILES (RATE LIMITS IN MBPS)
/ip hotspot profile set [ find default=yes ] use-radius=yes radius-accounting=yes radius-interim-update=1m login-by=http-chap,http-pap,mac-cookie,cookie http-cookie-lifetime=1d
${plansScript}

# 6. WALLED GARDEN (ALLOW TANZANIAN PAYMENT GATEWAYS BEFORE LOGIN)
/ip hotspot walled-garden ip
add dst-host="*vodacom.co.tz*" action=accept comment="Vodacom M-Pesa Portal"
add dst-host="*tigo.co.tz*" action=accept comment="Tigo Pesa"
add dst-host="*airtel.co.tz*" action=accept comment="Airtel Money"
add dst-host="*halotel.co.tz*" action=accept comment="Halopesa"
add dst-host="*azampay.com*" action=accept comment="AzamPay Gateway"
add dst-host="*selcom.net*" action=accept comment="Selcom Lipa"
add dst-host="*xcloud.co.tz*" action=accept comment="XCloud Central Server"
add dst-host="*.googleapis.com" action=accept comment="Google Fonts/CDN"

# 7. AUTOMATIC VOUCHER SYNC & HEALTH CHECK CRON SCRIPT
/system script add name="xcloud_sync" source={
  :log info "XCLOUD: Starting Cloud Synchronisation...";
  /tool fetch url="https://api.xcloud.co.tz/api/v1/router/ping?router_id=${router.id}&uptime=\$[/system resource get uptime]&cpu=\$[/system resource get cpu-load]" keep-result=no;
}
/system scheduler add name="xcloud_sync_scheduler" interval=1m on-event="xcloud_sync" start-time=startup

:put "======================================================="
:put "  XCLOUD TANZANIA RB941 CONFIGURATION APPLIED SUCCESSFULLY! "
:put "  Tunnel IP: ${router.tunnelIp} | Cloud Webhook Active!    "
:put "======================================================="
`;
}

export function generateWireguardScript(router: RouterDevice): string {
  return `# XCLOUD WIREGUARD CONFIG FOR MIKROTIK ROUTEROS v7
/interface wireguard add name=wg-xcloud listen-port=51820
/ip address add address=${router.tunnelIp}/24 interface=wg-xcloud network=10.8.0.0
/interface wireguard peers add interface=wg-xcloud public-key="${router.wireguardStatus.publicKey}" endpoint-address="vpn-tz1.xcloud.co.tz" endpoint-port=51820 allowed-address=10.8.0.0/24 persistent-keepalive=25s
`;
}

export function generateVoucherAddScript(vouchers: { code: string; planId: string; limitUptime?: string }[]): string {
  return `# BATCH IMPORT MIKROTIK HOTSPOT USERS
${vouchers.map((v) => `/ip hotspot user add name="${v.code}" password="${v.code}" profile="${v.planId}" ${v.limitUptime ? `limit-uptime=${v.limitUptime}` : ''} comment="XCloud TZ Voucher"`).join('\n')}
`;
}
